### ISSUE TITLE
buffactive change

### ISSUE THREAD

**Issue by bardicrune** [ThornyFFXI/Ashitacast#2]
Previously for v3 when checking for one of two buffs (SA|TA) being active the following could be used:

`<if buffactive="65|87">...</if>`

now the only way to accomplish the same is to use the advanced tag:

`<if advanced="($b_65=1)|($b_87=1)">...</if>`

This makes it a much more complex and less user friendly method.  Am I just missing something to simplify my xml or can the tag be re-implemented?

**Comment by ThornyFFXI** [comment]
Both XML-based systems are maintenance only, as lua is a full featured language and a much better way to implement swaps.  While you are welcome to use whichever you prefer, no new features are likely to be added to either version of ashitacast.
